export const dataArr = [
  {
    id: 'id1',
    name: 'Robert Brown',
    country: 'UK',
    phoneNumber: '+12345678900',
    signalPriority: 'MEDIUM',
    status: 'APPLIED',
    stars: 2,
    isNew: true,
    isFollowed: false,
  },
  // {
  //   id: 'id2',
  //   name: 'Emily Clark',
  //   country: 'Canada',
  //   phoneNumber: '+12345678901',
  //   signalPriority: 'HIGH',
  //   status: 'INTERVIEW',
  //   stars: 5,
  //   isNew: false,
  //   isFollowed: true,
  // },
  {
    id: 'id3',
    name: 'Alice Johnson',
    country: 'Australia',
    phoneNumber: '+12345678902',
    signalPriority: 'LOW',
    status: 'SHORTLISTED',
    stars: 3,
    isNew: true,
    isFollowed: true,
  },
  {
    id: 'id4',
    name: 'Sophia Young',
    country: 'Germany',
    phoneNumber: '+12345678903',
    signalPriority: 'MEDIUM',
    status: 'APPLIED',
    stars: 4,
    isNew: false,
    isFollowed: true,
  },
  // {
  //   id: 'id5',
  //   name: 'Michael Wilson',
  //   country: 'France',
  //   phoneNumber: '+12345678904',
  //   signalPriority: 'HIGH',
  //   status: 'INTERVIEW',
  //   stars: 2,
  //   isNew: true,
  //   isFollowed: false,
  // },
  {
    id: 'id6',
    name: 'Liam Martinez',
    country: 'India',
    phoneNumber: '+12345678905',
    signalPriority: 'LOW',
    status: 'SHORTLISTED',
    stars: 5,
    isNew: false,
    isFollowed: true,
  },
  // {
  //   id: 'id7',
  //   name: 'Lucy Davis',
  //   country: 'Japan',
  //   phoneNumber: '+12345678906',
  //   signalPriority: 'MEDIUM',
  //   status: 'APPLIED',
  //   stars: 3,
  //   isNew: true,
  //   isFollowed: true,
  // },
  {
    id: 'id8',
    name: 'William Harris',
    country: 'Brazil',
    phoneNumber: '+12345678907',
    signalPriority: 'HIGH',
    status: 'INTERVIEW',
    stars: 1,
    isNew: false,
    isFollowed: false,
  },
  {
    id: 'id9',
    name: 'James Lewis',
    country: 'South Africa',
    phoneNumber: '+12345678908',
    signalPriority: 'LOW',
    status: 'SHORTLISTED',
    stars: 4,
    isNew: true,
    isFollowed: true,
  },
  // {
  //   id: 'id10',
  //   name: 'John Doe',
  //   country: 'USA',
  //   phoneNumber: '+12345678909',
  //   signalPriority: 'MEDIUM',
  //   status: 'APPLIED',
  //   stars: 5,
  //   isNew: false,
  //   isFollowed: true,
  // },
  {
    id: 'id11',
    name: 'Olivia White',
    country: 'Canada',
    phoneNumber: '+12345678910',
    signalPriority: 'HIGH',
    status: 'INTERVIEW',
    stars: 3,
    isNew: true,
    isFollowed: false,
  },
  {
    id: 'id12',
    name: 'Jane Smith',
    country: 'UK',
    phoneNumber: '+12345678911',
    signalPriority: 'LOW',
    status: 'SHORTLISTED',
    stars: 4,
    isNew: false,
    isFollowed: true,
  },
];
